steps:
  deploy:
    image: docker:27-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd /home/antost/woodpecker-repos/calorie-tracker
      - git pull origin main
      - docker build -t antost360/calorie-tracker:latest .
      - cd /home/antost/homelab
      - docker compose up -d calorie-tracker
      - docker image prune -f
    when:
      - event: push
        branch: main
